version: "3.5"
services:
  cifs-client:
    image: shukriadams/cifs-client:0.0.1
    container_name: cifs-client
    privileged : true
    volumes:
    - ./fstab:/etc/fstab
    command: /bin/sh -c "mount -a && while true ;sleep 5; do continue; done"